#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# eval "$(docker-machine env dev2)"

test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh

source /usr/local/bin/aws_zsh_completer.sh

function _ec2ssh() { ssh $(cap $1 ec2:status | tail -n 1 | cut -f 6 -d " ") }
alias ec2ssh="_ec2ssh"

function _gitIgnoreAllVcsh() {
  for repo in $(vcsh list); do
    vcsh write-gitignore $repo
    vcsh $repo add -f .gitignore.d/$repo
    vcsh write-gitignore $repo
    vcsh $repo add .gitignore.d/$repo
    vcsh $repo commit -m "Add/update .gitignore.d/$repo"
  done
}
alias gitIgnoreAllVcsh="_gitIgnoreAllVcsh"
